### ISSUE TITLE
Audit farm components

### ISSUE THREAD

**Issue by janklimo** [pickle-finance/pf-core#100]
Can we please review farm components returned by core? Noticed them missing for Curve farms, Liquity, maybe more. See https://github.com/pickle-finance/pickle-ui/issues/294#issuecomment-1013808520

**Comment by robstryker** [comment]
Please be more specific. Do you need asset/depositToken/components?  or asset/depositToken/componentTokens?  or both? Are both strictly required? As i understand it we've had problems getting the component token counts.

**Comment by robstryker** [comment]
List of jars with no components:
sCRV
renBTCCRV
3poolCRV
steCRV
undefined
ALETH
LQTY
LOOKS
