### ISSUE TITLE
Data fixes

### ISSUE THREAD

**Issue by janklimo** [pickle-finance/pf-core#104]
SolarSwap is a protocol on Solana, should be Solarbeam:

https://app.solarbeam.io/exchange/swap

<img width="530" alt="Screen Shot 2022-01-22 at 15 11 27" src="https://user-images.githubusercontent.com/7811733/150630480-833651f4-ae77-46eb-948b-442c7f764db2.png">

**Comment by janklimo** [comment]
STELLA/USDC has the wrong pool link:
https://app.stellaswap.com/exchange/add/0x818ec0A7Fe18Ff94269904fCED6AE3DaE6d6dC0b/ETH

**Comment by janklimo** [comment]
CHE is recorded as CHERRY as farm component.

**Comment by janklimo** [comment]
JF is recorded as JSWAP as farm component.

**Comment by janklimo** [comment]
MAI is recorded as MIMATIC as farm component.

**Comment by janklimo** [comment]
<img width="636" alt="Screen Shot 2022-03-24 at 20 22 22" src="https://user-images.githubusercontent.com/7811733/159925380-ffbfd547-d89b-41d2-8c77-a9afcf4a002b.png">

wrong deposit token name

**Comment by robstryker** [comment]
> SolarSwap is a protocol on Solana, should be Solarbeam:
> 
> https://app.solarbeam.io/exchange/swap
> 
> <img alt="Screen Shot 2022-01-22 at 15 11 27" width="530" src="https://user-images.githubusercontent.com/7811733/150630480-833651f4-ae77-46eb-948b-442c7f764db2.png">

I am unsure what lines you are referring to or what the fix is here

**Comment by robstryker** [comment]
> STELLA/USDC has the wrong pool link: https://app.stellaswap.com/exchange/add/0x818ec0A7Fe18Ff94269904fCED6AE3DaE6d6dC0b/ETH

Fixed

**Comment by robstryker** [comment]
> JF is recorded as JSWAP as farm component.

JSWAP is the internal id we've given to this token. Is there a problem here? I don't see the problem.

**Comment by robstryker** [comment]
> MAI is recorded as MIMATIC as farm component.

MIMATIC is the internal id we've given to this token. Is there a problem here? I don't see the problem.

I'm a bit confused clearly.

**Comment by janklimo** [comment]
Whatever you define as a component is shown in the search component so the token names should match the official tickers:

<img width="606" alt="Screen Shot 2022-03-29 at 00 14 56" src="https://user-images.githubusercontent.com/7811733/160451968-0dea7ed1-8614-4701-9193-6616f11ce84c.png">

**Comment by rawbdor** [comment]
fixed the solarswap / solarbeam issue.
The rest of this... I'm really not sure how to proceed on.
