### ISSUE TITLE
User model lite

### ISSUE THREAD

**Issue by janklimo** [pickle-finance/pf-core#134]
I'm looking for an elegant helper that would take a `JarDefinition` with current provider and return all the data needed to render this view:

<img width="1470" alt="Screen Shot 2022-03-05 at 16 43 35" src="https://user-images.githubusercontent.com/7811733/156877868-27532c99-36b4-4bf7-9d3d-03993c9c7186.png">

Besides balances, we'll also need to know if we have an approval for the jar to spend the token. I think this can be a boolean to keep it simple.

The intended use case is:

1. When the user expands a farm row, fetch fresh data about allowances and balances for that jar
2. Upon successful transaction, refresh data
3. Keep this data in a store as a dictionary with jar api keys as keys, update it if transactions are made.
4. User model as it is is useful to list all of user's farms on the dashboard. This lite version will facilitate refreshing individual jar data on demand – only the farms user interacts with.

**Comment by rawbdor** [comment]
I have some light entry points that can generate a pfcore + user model for a single jar in about 8 seconds. But it doesn't have approvals built in. I assume we'd need approvals listed for the deposit token to the jar contract, and approvals for the ptoken to the chef...   i'll look into that next.
