### ISSUE TITLE
pickle-ui and pf-core reporting different cvx APR values for 3 jars.

### ISSUE THREAD

**Issue by MisterMard** [pickle-finance/pf-core#14]
- `cvxCRV`:
	- UI: CVX: 26.18%
	- CORE: CVX: 17.6%
- - -
01/01/2022 update 
crv: 10.60%
cvx: 15.91%
3crv: 4.45%

convex site shows
CRV vAPR | 17.33%
CVX vAPR | 30.52%
3crv vAPR | 5.71%
- - -
Optional (original issue for context)
- `stETH-ETH`:
	- UI: CVX: 0.23%
	- CORE:	CVX: 0.2%

- `mim3CRV`:
	- UI: CVX: 11.73%
	- CORE: CVX: 13.08%

- `Curve cvxCRV` and `cvxCRV` farms are reporting identical APR values for `lp` and `crv` rewards components (note: `cvxCRV` should not have an `lp` component, plus, the values in pickle-ui and in pfcore do not match what convex ui is reporting).

**Comment by rawbdor** [comment]
@MisterMard  can you verify this is still occurring?
