### ISSUE TITLE
Unify naming convention for jar and farm deposit token names

### ISSUE THREAD

**Issue by bcstryker** [pickle-finance/pf-core#15]
There are currently different naming conventions used for different the Jar deposit token names, farm nicknames, and farm deposit token names. I propose a standardization of the naming conventions as follows: 
```
Jar Deposit Token Name
    [protocol] [existing-pool-name]
    - or -
    [protocol] [currency](/[currency])*

Farm Nickname
    These should not be used anymore

Farm Deposit Token Name
    "p" + [jar-deposit-token-name]
```
See attached xlsx which contains all active jars from pf-core JSON output with new naming convention applied. There are some notes in the document regarding other things I've found in the data. Please disregard those for now, I will open new issues for them after some more investigation.

[proposedNamingConvention.xlsx](https://github.com/pickle-finance/pf-core/files/7447141/proposedNamingConvention.xlsx)

**Comment by bcstryker** [comment]
Working on a patch for this issue.

**Comment by bcstryker** [comment]
Noticed inconsistencies with protocols in jar and farm names. Some jar names include SUSHI, COMETH and QUICK while their farms use SLP, CLP and QLP. I feel we should pick one and stick with it.

**Comment by rawbdor** [comment]
merged
