### ISSUE TITLE
Change shape of user tokens response

### ISSUE THREAD

**Issue by janklimo** [pickle-finance/pf-core#153]
It's a common practice in Redux to normalize server response to an object allowing you to find records by an ID. This has a number of benefits:

1. O(1) complexity of looking up token data
2. Ability to merge partial updates, e.g. `state.tokens = { ...state.tokens, ...subsetOfTokensForTheCurrentChain }`
3. Update a specific token object when doing optimistic UI updates, e.g. set token allowance upon successful transaction, query on-chain data, update state with on-chain data.

I've been normalizing token data [in the current PR](https://github.com/pickle-finance/pickle-ui/pull/371/files#diff-3c8b5c16104ab4a7604e3f12c91f4eca3774afa6b32520b761ce9da7682eb58d) but since we have control over the source of the response we might as well do it there and simplify things. Here's the proposed change.

```diff
diff --git a/src/client/UserModel.ts b/src/client/UserModel.ts
index 7ada705..4c3a4de 100644
--- a/src/client/UserModel.ts
+++ b/src/client/UserModel.ts
@@ -28,7 +28,6 @@ import {
 } from "../Contracts/ContractsImpl";

 export interface UserTokenData {
-  assetKey: string;
   depositTokenBalance: string;
   pAssetBalance: string;
   jarAllowance: string;
@@ -36,8 +35,13 @@ export interface UserTokenData {
   farmAllowance: string;
   picklePending: string;
 }
+
+interface UserTokens {
+  [assetKey: string]: UserTokenData | undefined;
+}
+
 export interface UserData {
-  tokens: UserTokenData[];
+  tokens: UserTokens;
   earnings: IUserEarningsSummary;
   votes: IUserVote[];
   dill: IUserDillStats;
```

**Comment by rawbdor** [comment]
commit ed98f9b33b2a21cf45f95a7c1da151ead3d13041
Author: bwar <rawblem@gmail.com>
Date:   Tue Mar 22 11:16:20 2022 -0400
