### ISSUE TITLE
User model not returning allowances

### ISSUE THREAD

**Issue by janklimo** [pickle-finance/pf-core#154]
This will return zeros if a user just gave jar approval:

https://github.com/pickle-finance/pf-core/blob/7a829868d9668eef79ff786036f190d8a7a7ee3c/src/client/UserModel.ts#L423-L427

**Comment by robstryker** [comment]
I'm sorry, but I don't understand how that's wrong? If a user just gave jar approval, he probably has all zeros, no? I'm lost.

**Comment by robstryker** [comment]
I've added checks to ensure everything is zero, including allowances, now.  So if the field just doesn't exist, you can assume it's all zeros.

**Comment by janklimo** [comment]
That's correct, thanks
