### ISSUE TITLE
Curve Gauge (polygon, arbitrum): use claimable_reward_write to query claimable rewards

### ISSUE THREAD

**Issue by gs1115** [pickle-finance/pf-core#20]
Polycon 3CRV jar (p3crv) and Arbitrum TriCrypto jar are affected.

p3crv gauge code:
https://polygonscan.com/address/0x19793B454D3AfC7b454F206Ffe95aDE26cA6912c#code
arbi-tricrypto gauge code:
https://arbiscan.io/address/0x97E2768e8E73511cA874545DC5Ff8067eB19B787#code
(Code & ABI look the same)

Reading the comments under `claimable_reward` in the code: 
      @dev This call does not consider pending claimable amount in `reward_contract`.
         Off-chain callers should instead use `claimable_reward_write` as a
         view method.

Also, official curve document suggests the same. 
https://curve.readthedocs.io/dao-gauges.html#LiquidityGaugeV3.claimable_reward

It seems that `claimable_reward` only returns a local snapshot value that is cached when a deposit or withdrawal is made to the gauge. If there is no deposit/withdrawal, this method will return a stale value. There seems to be a hidden claimable reward value, which is accessible via `claimable_reward_write` method.

Larry suggests to use `callStatic` to issue `claimable_reward_write` as a view method.

My suggested solution:

1. curveThirdPartyGaugeAbi used by these two jars is not correct. src/Contracts/ABIs/curve-external-gauge.abi.ts
 needs to be updated with the Contract ABI given below the code section at https://arbiscan.io/address/0x97E2768e8E73511cA874545DC5Ff8067eB19B787#code
2. https://github.com/pickle-finance/pf-core/blob/07085744ea912582198b45fd295cfcac6a8e5641/src/behavior/impl/crv-tricrypto.ts#L73
https://github.com/pickle-finance/pf-core/blob/20733242739f56b5e2e8defd2225fae22f29e9cb/src/behavior/impl/p3crv.ts#L71
https://github.com/pickle-finance/pf-core/blob/20733242739f56b5e2e8defd2225fae22f29e9cb/src/behavior/impl/p3crv.ts#L76
change to `gauge.callStatic.claimable_reward_write(`

The ETH mainnet Curve gauge does not seem to be affected.

**Comment by gs1115** [comment]
Initially wrote `staticCall` -> should be `callStatic`. edited

**Comment by rawbdor** [comment]
Fixed in the very bad commit message:

* 319457a - Made requested changes (2 minutes ago) <bcstryker>

**Comment by rawbdor** [comment]
I've verified the patch provides larger values for tricrypto and am3crv.
