### ISSUE TITLE
UserModel not returning balances of non-standard assets

### ISSUE THREAD

**Issue by janklimo** [pickle-finance/pf-core#202]
I believe this is because here

https://github.com/pickle-finance/pf-core/blob/3eee4b584b84bf3ed0ec6741a1c55f7d10e8ef92/src/client/UserModel.ts#L335

we only work with jars. As a result, we return no values for B.Protocol jar, for example.

To debug:
http://app.pickle.finance/v2/farms?debug=0x69d962a66e5bfff0875cb7a6345be283bc6437d2

is expected to have deposited balance in the B.Protocol jar, [as of this tx](https://etherscan.io/tx/0x1d2c6d14a002e93296f8a887317c343c8aa5ae5ea9ad5bbd47b9cf9009812909).

**Comment by MisterMard** [comment]
@janklimo 
commit 6c244192bd14fe6c04b34ef98b446832e4d099c8 attempts to resolve this. Please review and close if fixed.

**Comment by janklimo** [comment]
Thank you @MisterMard
