### ISSUE TITLE
Gnosis chain RPC

### ISSUE THREAD

**Issue by janklimo** [pickle-finance/pf-core#207]
https://rpc.ankr.com/gnosis to be added as an RPC entry, possibly a primary one since the current one is very unstable

**Comment by rawbdor** [comment]
In pfcore, this was apparently fixed by https://github.com/pickle-finance/pf-core/commit/c83913c8cb192fa3b5772c76bd62bee9713143b8,   a huge commit that changed all the files, had no pull request, and apparently fixed arbitrary other issues along the way without any comment in the commit. 

Awesome.
