### ISSUE TITLE
Jars that need documentation

### ISSUE THREAD

**Issue by rawbdor** [pickle-finance/pf-core#69]
- [ ] Docs missing for asset yveCRV-ETH
- [ ] Docs missing for asset saddled4
- [ ] Docs missing for asset LUSD-ETH
- [ ] Docs missing for asset CVX-ETH
- [ ] Docs missing for asset RLY-ETH
- [ ] Docs missing for asset cvxCRVlp
- [ ] Docs missing for asset cvxcrv
- [ ] Docs missing for asset CRVETH
- [ ] Docs missing for asset TRU-ETH
- [ ] Docs missing for asset RBN-ETH
- [ ] Docs missing for asset QLP-QIMATIC
- [ ] Docs missing for asset PSLP-WORK
- [ ] Docs missing for asset ArbitrumSlpGohmEth
- [ ] Docs missing for asset ArbitrumSlpMagicEth
- [ ] Docs missing for asset DodoHndEth
- [ ] Docs missing for asset DodoUsdc
- [ ] Docs missing for asset CrvTricrypto
- [ ] Docs missing for asset BalTricrypto
- [ ] Docs missing for asset CherryOktChe
- [ ] Docs missing for asset CherryUsdtChe
- [ ] Docs missing for asset CherryOktUsdt
- [ ] Docs missing for asset CherryEthkUsdt
- [ ] Docs missing for asset BxhUsdt
- [ ] Docs missing for asset BXH-ETHK-BTCK
- [ ] Docs missing for asset JSWAP-JF-USDT
- [ ] Docs missing for asset JSWAP-BTCK-USDT
- [ ] Docs missing for asset JSWAP-ETHK-USDT
- [ ] Docs missing for asset JSWAP-DAIK-USDT
- [ ] Docs missing for asset JSWAP-DAIK-USDC
- [ ] Docs missing for asset HSLP-ETH-DAI
- [ ] Docs missing for asset HSLP-WBTC-ETH
- [ ] Docs missing for asset HSLP-ETH-ONE
- [ ] Docs missing for asset SLP-SOLAR-MOVR
- [ ] Docs missing for asset SLP-DAI-USDC
- [ ] Docs missing for asset SLP-MOVR-USDC
- [ ] Docs missing for asset SLP-SOLAR-USDC
- [ ] Docs missing for asset SLP-USDT-USDC
- [ ] Docs missing for asset SLP-BUSD-USDC
- [ ] Docs missing for asset SLP-ETH-USDC
- [ ] Docs missing for asset SLP-BNB-BUSD
- [ ] Docs missing for asset SLP-WBTC-USDC
- [ ] Docs missing for asset SLP-AVAX-MOVR
- [ ] Docs missing for asset SLP-MAI-USDC
- [ ] Docs missing for asset SLP-MIM-USDC
- [ ] Docs missing for asset SLP-MOVR-FTM
- [ ] Docs missing for asset SLP-MOVR-RIB
- [ ] Docs missing for asset SLP-MOVR-RELAY
- [ ] Docs missing for asset SLP-SOLAR-RIB
- [ ] Docs missing for asset SLP-PETS-MOVR
- [ ] Docs missing for asset SLP-FRAX-MOVR
- [ ] Docs missing for asset SLP-MIM-MOVR
- [ ] Docs missing for asset SLP-BNB-MOVR
- [ ] Docs missing for asset SLP-ETH-MOVR
- [ ] Docs missing for asset VLP-CRO-BIFI
- [ ] Docs missing for asset VLP-CRO-DAI
- [ ] Docs missing for asset VLP-CRO-SHIB
- [ ] Docs missing for asset VLP-CRO-USDC
- [ ] Docs missing for asset VLP-CRO-USDT
- [ ] Docs missing for asset VLP-VVS-USDC
- [ ] Docs missing for asset VLP-VVS-USDT
- [ ] Docs missing for asset VLP-CRO-VVS
- [ ] Docs missing for asset VLP-CRO-BTC
- [ ] Docs missing for asset VLP-USDC-USDT
- [ ] Docs missing for asset VLP-CRO-ETH
- [ ] Docs missing for asset TLP-NEAR-USDC
- [ ] Docs missing for asset TLP-NEAR-ETH
- [ ] Docs missing for asset TLP-NEAR-USDT
- [ ] Docs missing for asset TLP-NEAR-TRI
- [ ] Docs missing for asset TLP-USDT/USDC
- [ ] Docs missing for asset TLP-BTC/NEAR
- [ ] Docs missing for asset TLP-AURORA/TRI
- [ ] Docs missing for asset TLP-AURORA/ETH
- [ ] Docs missing for asset WLP-WANNA-NEAR
- [ ] Docs missing for asset WLP-AURORA-NEAR
- [ ] Docs missing for asset WLP-ETH-BTC
- [ ] Docs missing for asset WLP-NEAR-BTC
- [ ] Docs missing for asset WLP-NEAR-DAI
- [ ] Docs missing for asset WLP-NEAR-ETH
- [ ] Docs missing for asset WLP-USDC-NEAR
- [ ] Docs missing for asset WLP-USDT-NEAR
- [ ] Docs missing for asset WLP-USDT-USDC
- [ ] Docs missing for asset WLP-WANNA-USDC
- [ ] Docs missing for asset WLP-USDT-WANNA
- [ ] Docs missing for asset NLP-BTC/NEAR
- [ ] Docs missing for asset NLP-PAD/USDT
- [ ] Docs missing for asset NLP-PAD/USDC
- [ ] Docs missing for asset NLP-PAD/ETH
- [ ] Docs missing for asset NLP-PAD/NEAR
- [ ] Docs missing for asset NLP-PAD/FRAX
- [ ] Docs missing for asset pickle-eth
- [ ] Docs missing for asset PBAMM
- [ ] Docs missing for asset sushi-pickle-eth

**Comment by rawbdor** [comment]
Assigned to bcs and ape to try to fill in the missing details.

**Comment by bcstryker** [comment]
Use this [google sheet](https://docs.google.com/spreadsheets/d/1k6fI1ShP1wwACPKcqaNTMCzu4sE5Z7OW5uHwSEbZs2g/edit?usp=sharing) for documentation

**Comment by sevenz-eth** [comment]
how do you want this documents written? in 1 sheet or having their own chain sheet?
@bcstryker @amatureApe 

I can help with the docs if AmatureApe is whipping jars up.

**Comment by rawbdor** [comment]
This is done
